stages:
  - deploy

deploy_to_github:
  stage: deploy
  image: alpine:latest
  before_script:
    # Install git and other required tools
    - apk add --no-cache git curl jq
    
    # Set up git configuration
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "$GIT_NAME"
    
  script:
    # Echo useful information for debugging
    - echo "Starting GitHub sync process..."
    
    # Clone the GitLab repository (with mirror to include all refs)
    - echo "Cloning repository from GitLab..."
    - git clone --mirror https://oauth2:$GITLAB_PERSONAL_ACCESS_TOKEN@gitlab.com/nguyenngocbinh/stockbox.git || (echo "Clone failed"; exit 1)
    - cd stockbox.git
    
    # Add GitHub remote
    - echo "Adding GitHub remote..."
    - git remote add github https://$GITHUB_TOKEN@github.com/nguyenngocbinh/stockbox.git
    
    # Check GitHub branch protection status
    - echo "Checking GitHub branch protection..."
    - |
      if curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/nguyenngocbinh/stockbox/branches/main/protection | grep -q "protected"; then
        echo "Main branch is protected on GitHub. Using alternative push strategy..."
        
        # Push all branches except protected ones
        git push github +refs/heads/*:refs/heads/* --prune || echo "Some branches were not pushed, likely due to protection"
        
        # Push all tags
        git push github +refs/tags/*:refs/tags/* --prune
        
        # Push all other refs except pipelines
        git for-each-ref --format="%(refname)" | grep -v "refs/heads/" | grep -v "refs/tags/" | grep -v "refs/pipelines/" | 
        while read ref; do
          git push github $ref:$ref || echo "Failed to push $ref, skipping"
        done
        
        echo "Push completed with exclusions for protected branches"
      else
        # Standard mirror push if no protection
        echo "Pushing all refs to GitHub..."
        git push --mirror github || (echo "Push failed"; exit 1)
      fi
      
    # Verify the result
    - echo "GitHub sync complete."
    
  only:
    - main
  
  # Add retry logic in case of temporary network issues
  retry: 2
  
  # Use environment variables for credentials instead of hardcoding
  variables:
    GIT_EMAIL: "${GIT_EMAIL:-nguyenngocbinhneu@gmail.com}"
    GIT_NAME: "${GIT_NAME:-Nguyen Ngoc Binh}"