stages:
  - deploy

deploy_to_github:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.email "nguyenngocbinhneu@gmail.com"
    - git config --global user.name "Nguyen Ngoc Binh"
    - echo "Cloning repository..."
    - git clone --mirror https://oauth2:$GITLAB_PERSONAL_ACCESS_TOKEN@gitlab.com/nguyenngocbinh/stockbox.git || (echo "Clone failed"; exit 1)
    - cd stockbox.git
    - echo "Adding GitHub remote..."
    - git remote add github https://$GITHUB_TOKEN@github.com/nguyenngocbinh/stockbox.git
    - echo "Pushing to GitHub..."
    - git push --mirror github || (echo "Push failed"; exit 1)
  only:
    - main
