stages:
  - deploy

deploy_to_github:
  stage: deploy
  image: alpine:latest
  before_script:
    # Install git
    - apk add --no-cache git bash
    
    # Set up git configuration
    - git config --global user.email "nguyenngocbinhneu@gmail.com"
    - git config --global user.name "Nguyen Ngoc Binh"
    
  script:
    - echo "Starting GitHub sync process to dev branch..."
    
    # Create a fresh clone of the repository
    - echo "Cloning repository from GitLab..."
    - git clone https://oauth2:$GITLAB_PERSONAL_ACCESS_TOKEN@gitlab.com/nguyenngocbinh/stockbox.git
    - cd stockbox
    
    # Add GitHub as a remote
    - echo "Adding GitHub remote..."
    - git remote add github https://$GITHUB_TOKEN@github.com/nguyenngocbinh/stockbox.git
    
    # Fetch from GitHub to see current state
    - echo "Fetching from GitHub..."
    - git fetch github
    
    # Create or update dev branch from main
    - echo "Creating/updating dev branch from main..."
    - git checkout main
    - git checkout -B dev  # Force create/reset the dev branch based on current main
    
    # Push dev branch to GitHub
    - echo "Pushing dev branch to GitHub..."
    - git push -f github dev
    
    # Also push gh-pages if it exists
    - echo "Checking for gh-pages branch..."
    - |
      if git branch -a | grep -q "remotes/origin/gh-pages"; then
        echo "Found gh-pages branch, pushing to GitHub..."
        git checkout gh-pages || git checkout -b gh-pages origin/gh-pages
        git push -f github gh-pages
      fi
    
    # Push tags as well
    - echo "Pushing tags..."
    - git push github --tags
    
    # Summary
    - echo "GitHub sync completed. Your main branch content has been pushed to 'dev' branch on GitHub."
    
  only:
    - main
  
  # Add retry logic for network issues
  retry: 2