on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true 
          # Uncomment below and fill to pin a version
          # version: 0.9.600
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # or specify a specific version like '3.8'
          
      # Add your Python dependencies installation here if needed
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any other dependencies you need, for example:
          pip install jupyter numpy scipy pandas openpyxl
      
      # If you need to run a Python script before rendering the Quarto file
      #- name: Run Python Script
      #  run: python path_to_your_script.py

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # This secret is always available for GitHub actions
